server:
  port: 9999


logging:
  level:
    com.bs.payment.modules.trade.dao: debug


spring:
  datasource:
    druid:
      driver-class-name: com.mysql.jdbc.Driver
      url: jdbc:mysql://localhost:3303/bs?useUnicode=true&characterEncoding=utf-8&zeroDateTimeBehavior=round&autoReconnect=true&serverTimezone=UTC 
      username: zhenling
      password: 123321
      initial-size: 2
      max-active: 10
      min-idle: 2
      max-wait: 3000
      pool-prepared-statements: true
      validation-query: SELECT 1
      test-while-idle: true 

management:
  endpoints:
    web:
      exposure:
        include:
        - info
        - health
        - env
        - env-toMatch
        - configprops
        - beans
