spring:
  datasource:
    druid:
      driver-class-name: com.mysql.jdbc.Driver
      url: jdbc:mysql://mysql.server.com:3306/paycenter?useUnicode=true&characterEncoding=utf-8&zeroDateTimeBehavior=round
      username: intbee
      password: intbee@mysql
      initial-size: 10
      min-idle: 20
      max-active: 100
      max-wait: 3000
  kafka:
    bootstrap-servers: 10.0.1.193:9092
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.apache.kafka.common.serialization.StringSerializer
    consumer:
      group-id: zc-payment-consumer-group
      auto-offset-reset: earliest
      enable-auto-commit: true
      auto-commit-interval: 100
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer

douyin:
  appid: 800062265409
  mchid: 1900006226
  sercet: eyjna2w9wyb8vmftrxjh878r2g60xsgiuc4pjrt7
  public-key: MIGfMA0GCSqGSIb3DQEBAQUAA4GNADCBiQKBgQDOZZ7iAkS3oN970+yDONe5TPhPrLHoNOZOjJjackEtgbptdy4PYGBGdeAUAz75TO7YUGESCM+JbyOz1YzkMfKl2HwYdoePEe8qzfk5CPq6VAhYJjDFA/M+BAZ6gppWTjKnwMcHVK4l2qiepKmsw6bwf/kkLTV9l13r6Iq5U+vrmwIDAQAB
  url: https://tp-pay.snssdk.com/gateway

payment:
  domain: http://dev-payv3.intbee.com
  bill-download-folder: ./bill
  app:
    101:
      alipay_lite:
          remark:  小程序-支付宝
          appid: 2019090566908649
          mchid: 2088221861486600
          environment: dev
          sign-type: RSA2
          private-key: MIIEvgIBADANBgkqhkiG9w0BAQEFAASCBKgwggSkAgEAAoIBAQCSLmuuALlXNDCjkzpivsh/EfCRIeNSppCk8xwm38/hcWUMXFQgVoZq80ZVVacnuS1kO4ZJVRlgGHd0yQgT6EWifZk6IuiikGFQ7DCklLzZ9gqiZ9zy2Ab9DV7aHL0SayhWAc1AtDfjp+8cAkTaq1ilUtbuNVItIsN1W8ILm65e3YuWemfmJuHyd7IJ8cj+HKCltuITQdDnGLLwrlacv2ZRHcUk5jWx5gsm0/uYrS2SHRCFRBDW6NLO+0mVC/wZxuFau9cF3TjHDKVmHABAp2AUh9+kyEMAR8n5vguFQB3+a+u5AYRnuqYpP5GrUEtR/0H4LDvklAeyJN0TGIJ8JbCHAgMBAAECggEBAIzXauoISoppf19qz7sqA/TiLP04QFR2pTA4B2yxARI99dTV9DwAAZxz7dT0JIwST1iePUDUXBGJITcFJeJATS9EgehQkAFoyEp2dltr7xS1iQN2vJvBZeJUCoptXAGt+vv62m439Q1D1Q4QZZSluE/5I5n5B8bzEo01Lh2PDo7Yu1IV3YR9ZYxFiM+yOIrnK7MNaoCi+M2GwYgybxLeZr2e9b9PLwHxOY6dstrDBZRnB4rYNMJPzq+eWuXUTvqXUR2FJ7Lj7bVKJvkUsy5e9coO7IgtPFRnGoGvhcXhZlBS3Sdv9qijXoAQkp+6IIS+smvbBJDfzaSiDfUwN2g9/hECgYEA7Qhpv3O+g5bvm5oBWuuwGP2goior/QSY6tNZGdtO3mwzAfCg6mYocqzXQsp2dDGg0Fx5lqWPRxBTl7U+sxK+8/C7Lr8Upxt/kT6a/QKGOt2ewPRbKEQ7poZwGyrB4WXcUPVt0lcgCrWRgydWCGUVXdmzkKfwMZuMWTdkmZbpNIkCgYEAneDtBsXGwZ/F5y7/WEBT6On+M4+Xz3rTG/lEIZUh4ybxPmvKV6tGYqPnSPMqQXxcNKuEuZE8STyIUAHJxV5uoLc3JWZY/hfVZ/vhkY1ROXtYGX/P6NLb8QMIbzC3jjKfjFJFb2sCqwnyouKV30aMjn6HIgUXNg46m3L60icwmI8CgYAtf8PswCb902dDExjXfw5afbTr6/RtqQhBazhbQkGtaE+SO8JnvBxfhtX7OCnsu+oGlPmx9S2/kl65bE0QyrRk1vzXSE6KlTizhLTzhByICCqFF2K4JADfQkcar+ZvgcH8uF/QVHEOHTRFXLOjAORNE5DoX5Q3sYgLSBrDcLhrIQKBgQCWUvE9LpmWCQxFmKE2pWF/9zS8YW/59QgHrarqkvYGNDEl7zpliUZma4uwESBd5AxjdiDVE+2kCgf8rgcxbz3Et07BxJbdsVHYRaO8lCMPqVr0RJdxJzyWWf3w6SENOzRhRoComuqacsldwINVafYxQ1Zl1RUJujihhLQ/32LNDwKBgDrIiZB7CaX+pAV4d05L5w6Z69yZrIkunzPK+UcvDvSa1Q+oN8BqJ4F4qhvo3LwExEuPap2txQmVvOWWztCrAo9Ezuv9x+sJqVO7HEMRKSJJsdqnSijPRNJS90XKnNVhDdEjb9BIHb+Q/rMB7BhClp5YAUWJDcD0Do6LcMA3Qaw5
          public-key: MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAiupgAgDsPsvSFvUHaLSrORS+UiHa74ZH+JX0uxneJMcslnAR0nkNNu/FUShPwBP0bNJU2X5JET4NGxcyPU5y/v4shzbUWrL2MuARyaXW2JFcabQxntdByhutsm7GOiaHhiuSzq0jIPEqCT9PNXyW/Y7oGdCO8JNMOVjrzMPcAuCerXyC9m3SBDCo69UaDJKy9V6dFR1OdtxMNPF24GKSymV0TpcXxBos1ckkJfPFWqq5MQbPNFdviYOceeuQL2cNtHX3eOhlaaZiXPyI/IuSpfabXOSaTiaop/cNBuCA0Kb4mWmBAowsT+mUHzasPNx4Dv/tRPyunReV7IWyXBlZ+wIDAQAB
      alipay:
        remark: 智蜂-支付宝
        appid: 2016052401436400
        mchid: 2088221861486600
        private-key: MIICdgIBADANBgkqhkiG9w0BAQEFAASCAmAwggJcAgEAAoGBAJzAkjQpzJ34jaCSwhuIVWL+1cHBmtv8L5e/3ABufLB+23QqGHqXwpOYM25TAeHzzcjsFZi8s2sIcxADbZZrBZS+30S/DxzTEJlufoVYg4jPnfjwedKhcvfvr79iNSEFUTOxP04ESxOHoBIW+Ob57x01e/+la++CS22T2rmvPksvAgMBAAECgYAET181w/h2V4E9awufSi5e3HbwLuydI+ADIilgcalICRTrqsSlikq1WDgBzpJ8rgF4htVJL9cXGFJhnFaFDkhG9bxY2IZJmx9uVyJVOzc9kDpaYhsNiBe1RHfrst5wOs29p3T3tlt5z5ERSAK6FPzcA7YVzEIuH9U+0KY+Dk0P8QJBAMoT+KlORI71ckjhghLcQCs0UyWzSlcpTGzhah3CtmJGau0Uqc2banCh+xjFSYibB8Y/cEjnnEAu6miH3a0Uhf0CQQDGlGCz2h0b5Ydi47V8I58Xx+Q8ORZ52GS84jLGjvUdgXwqXVWbGVUfrP4e4BFoYwALNYbJ6No3sCrR9P8pyEebAkApB/MWlYDQMkA5UiiyIayZ2S8E2am/lvAgr4h3cIDN5ZRyfR6ZU/RB2HH+rphmt2vVsi3fb7/HPH92KBg3u5IVAkBSv0+Qgknw7vM8fOCKKxnHQg9UHQHFoitQHf3EiZuQQP2pdZ0PdT3oZiC6Yuo+EkrZYOOazUHpRKqDNNEC6ycTAkEAqCd9GrBrW7K5eJ9+kReD2Tad7jDEI49sAwrTrpQccYwFdYIsBD57KTSanjn1BsuOBxTXOu0Lw4EkaJjq0+NTOQ==
        public-key: MIGfMA0GCSqGSIb3DQEBAQUAA4GNADCBiQKBgQDDI6d306Q8fIfCOaTXyiUeJHkrIvYISRcc73s3vF1ZT7XN8RNPwJxo8pWaJMmvyTn9N4HQ632qJBVHf8sxHi/fEsraprwCtzvzQETrNRwVxLO5jVmRGi60j8Ue1efIlzPXV9je9mkjzOmdssymZkh2QhUrCmZYI/FCEa3/cNMW0QIDAQAB
      wx:
        remark: 智蜂-微信公众号
        key: d195f111fd3bf436951b90973f0ccac8
        appid: wx9b5cb757426e00d9
        mchid: 1429146602
        cert-path: classpath:cert/wx/apiclient_cert-1429146602.p12
      wx_lite:
          remark: 小程序-微信
          key: d195f111fd3bf436951b90973f0ccac8
          appid: wxc9d0a70977ecf5fe
          mchid: 1429146602
          cert-path: classpath:cert/wx/apiclient_cert-1429146602.p12
    501:
      wx:
        remark: 高校通-微信
        key: d195f111fd3bf436951b90973f0ccac8
        appid: wx1e86ddc5b2485ab2
        mchid: 1429146602
        cert-path: classpath:cert/wx/apiclient_cert-501-lite.p12
      wx_lite:
        remark:  高校通-微信小程序
        key: d195f111fd3bf436951b90973f0ccac8
        appid: wx1e86ddc5b2485ab2
        mchid: 1429146602
        cert-path: classpath:cert/wx/apiclient_cert-501-lite.p12
    503:
      alipay:
        remark: 全球带-支付宝
        appid: 2016052401436400
        mchid: 2088221861486600
        environment: dev
        sign-type: RSA2
        private-key: MIICdgIBADANBgkqhkiG9w0BAQEFAASCAmAwggJcAgEAAoGBAJzAkjQpzJ34jaCSwhuIVWL+1cHBmtv8L5e/3ABufLB+23QqGHqXwpOYM25TAeHzzcjsFZi8s2sIcxADbZZrBZS+30S/DxzTEJlufoVYg4jPnfjwedKhcvfvr79iNSEFUTOxP04ESxOHoBIW+Ob57x01e/+la++CS22T2rmvPksvAgMBAAECgYAET181w/h2V4E9awufSi5e3HbwLuydI+ADIilgcalICRTrqsSlikq1WDgBzpJ8rgF4htVJL9cXGFJhnFaFDkhG9bxY2IZJmx9uVyJVOzc9kDpaYhsNiBe1RHfrst5wOs29p3T3tlt5z5ERSAK6FPzcA7YVzEIuH9U+0KY+Dk0P8QJBAMoT+KlORI71ckjhghLcQCs0UyWzSlcpTGzhah3CtmJGau0Uqc2banCh+xjFSYibB8Y/cEjnnEAu6miH3a0Uhf0CQQDGlGCz2h0b5Ydi47V8I58Xx+Q8ORZ52GS84jLGjvUdgXwqXVWbGVUfrP4e4BFoYwALNYbJ6No3sCrR9P8pyEebAkApB/MWlYDQMkA5UiiyIayZ2S8E2am/lvAgr4h3cIDN5ZRyfR6ZU/RB2HH+rphmt2vVsi3fb7/HPH92KBg3u5IVAkBSv0+Qgknw7vM8fOCKKxnHQg9UHQHFoitQHf3EiZuQQP2pdZ0PdT3oZiC6Yuo+EkrZYOOazUHpRKqDNNEC6ycTAkEAqCd9GrBrW7K5eJ9+kReD2Tad7jDEI49sAwrTrpQccYwFdYIsBD57KTSanjn1BsuOBxTXOu0Lw4EkaJjq0+NTOQ==
        public-key: MIGfMA0GCSqGSIb3DQEBAQUAA4GNADCBiQKBgQDDI6d306Q8fIfCOaTXyiUeJHkrIvYISRcc73s3vF1ZT7XN8RNPwJxo8pWaJMmvyTn9N4HQ632qJBVHf8sxHi/fEsraprwCtzvzQETrNRwVxLO5jVmRGi60j8Ue1efIlzPXV9je9mkjzOmdssymZkh2QhUrCmZYI/FCEa3/cNMW0QIDAQAB
      wx:
        remark: 全球带-微信
        key: 6RPA3YLKonTECiHH9uDGbYw0MdJUK5QJ
        appid: wxd86049a121654669
        mchid: 1505417821
        cert-path: classpath:cert/wx/apiclient_cert-503-app.p12

management:
  endpoints:
    web:
      exposure:
        include:
        - info
        - health
        - env
        - env-toMatch
        - configprops
        - beans
      cors:
        allowed-origins:
        - '*'